Fix build with gcc-13
:Release Notes:
Add missing include.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/746825

TOPDIR/BUILD/work/qemux86_64-webos-linux/g-media-pipeline/1.0.0-gav.52/git/src/./parser/parser.h: In member function 'gint64 gmp::parser::Parser::get_start_time()':
TOPDIR/BUILD/work/qemux86_64-webos-linux/g-media-pipeline/1.0.0-gav.52/git/src/./parser/parser.h:125:20: error: 'strcmp' is not a member of 'std'; did you mean 'strcmp'?
  125 |           if (std::strcmp(match.str().c_str(), "start") == 0) {
      |                    ^~~~~~

introduced in:
http://gpro.lge.com/c/webosose/g-media-pipeline/+/383570
http://gpro.lge.com/c/webos-pro/meta-lg-webos/+/383763

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRQ-5208] [OSE] Fix static issues for g-media-pipeline

Change-Id: Idb92cb3511be09ca421887b67805afb8617ede47